#!/bin/bash
usage()
{
cat << EOF
usage: $0

Check if an LCLS1 cnf file can be parsed

EOF
}

if [[ ($1 == "--help") || ($1 == "-h") ]]; then
	usage
	exit 0
fi

HUTCH=$(get_info --gethutch)

LCLS2_HUTCHES="rix, tmo, ued"
if echo "$LCLS2_HUTCHES" | grep -iw "$HUTCH" > /dev/null; then
    # shellcheck disable=SC1090
    source /reg/g/pcds/dist/pds/"$HUTCH"/scripts/setup_env.sh
    PROCMGR='procmgr'
else
    PROCMGR="/reg/g/pcds/dist/pds/$HUTCH/current/tools/procmgr/procmgr"
fi

CNFEXT=.cnf
CNFFILE="$HUTCH"$CNFEXT
if [ "$HOSTNAME" == 'cxi-daq' ]; then
    PEXT=_0
    CNFFILE="$HUTCH"$PEXT$CNFEXT
elif [ "$HOSTNAME" == 'cxi-monitor' ]; then
    PEXT=_1
    CNFFILE="$HUTCH"$PEXT$CNFEXT
fi

STATUS=$($PROCMGR status /reg/g/pcds/dist/pds/"$HUTCH"/scripts/"$CNFFILE" control_gui)
ISOK=$(echo "$STATUS" | grep -c platform)
if [[ $ISOK == 0 ]]; then
    echo The cnf file for "$HUTCH" can be parsed
else
    echo WARNING: the cnf file for "$HUTCH" cannot parsed!
fi
