#!/bin/bash
usage()
{
cat << EOF
usage: $0

Check if an LCLS1 cnf file can be parsed

EOF
}

if [[ ($1 == "--help") || ($1 == "-h") ]]; then
	usage
	exit 0
fi

HUTCH=$(get_info --gethutch)
DAQTYPE=$(get_info --daq)

if [[ $DAQTYPE == 'LCLS2' ]]; then
    echo 'LCLS2 no longer uses cnf files!'
    exit 0
fi

PROCMGR="/reg/g/pcds/dist/pds/$HUTCH/current/tools/procmgr/procmgr"

CNFEXT=.cnf
CNFFILE="$HUTCH"$CNFEXT
if [ "$HOSTNAME" == 'cxi-daq' ]; then
    PEXT=_0
    CNFFILE="$HUTCH"$PEXT$CNFEXT
elif [ "$HOSTNAME" == 'cxi-monitor' ]; then
    PEXT=_1
    CNFFILE="$HUTCH"$PEXT$CNFEXT
fi

STATUS=$($PROCMGR status /reg/g/pcds/dist/pds/"$HUTCH"/scripts/"$CNFFILE" control_gui)
ISOK=$(echo "$STATUS" | grep -c platform)
if [[ $ISOK == 0 ]]; then
    echo Good, the cnf file for "$HUTCH" can be parsed.
else
    echo WARNING: the cnf file for "$HUTCH" cannot parsed!
fi
