#!/bin/bash
usage()
{
cat << EOF
usage: $0 [desktop number]

Waits for the LCLS-I daq windows to load, then exits.
EOF
}

if [[ ($1 == "--help") || ($1 == "-h") ]]; then
	usage
	exit 0
fi

source /reg/g/pcds/setup/pathmunge.sh
ldpathmunge /usr/local/lib


if [[ $# -gt 0 ]]; then
    SEARCHOPT='--onlyvisible --maxdepth 2 --limit 1 --all --desktop '$1' --sync '
else
    SEARCHOPT='--onlyvisible --maxdepth 2 --limit 1 --all --sync '
fi
proc=$(xdotool search "$SEARCHOPT" --name 'ProcStat')
ami=$(xdotool search "$SEARCHOPT" --name 'DAQ Online Monitoring')
env=$(xdotool search "$SEARCHOPT" --name 'Env')
crwin=$(xdotool search "$SEARCHOPT" --name 'DAQ Control')
echo "$proc $ami $env $crwin"
exit
