#!/bin/bash

programLen=$0

usage()
{
cat << EOF
usage: $0 options

Waits for the LCLS-I daq windows to load, then exits.

${0:2:${#programLen}} [desktop number]

EOF
}

if [[ $1 =~ ^(h|-h|-help|--help) ]]; then
	usage
	exit 0
fi

source /reg/g/pcds/setup/pathmunge.sh
ldpathmunge /usr/local/lib


if [[ $# > 0 ]]; then
    SEARCHOPT='--onlyvisible --maxdepth 2 --limit 1 --all --desktop '$1' --sync '
else 
    SEARCHOPT='--onlyvisible --maxdepth 2 --limit 1 --all --sync '
fi
proc=`xdotool search $SEARCHOPT --name 'ProcStat'`
ami=`xdotool search $SEARCHOPT --name 'DAQ Online Monitoring'`
env=`xdotool search $SEARCHOPT --name 'Env'`
crwin=`xdotool search $SEARCHOPT --name 'DAQ Control'` 
echo $proc $ami $env $crwin
exit