#!/usr/bin/env bash
# Source this to activate a pcds conda environment.
# By default, this activates the latest environment.
# Use export PCDS_CONDA_VER=<version> before running to pick a different env.
unset LD_LIBRARY_PATH
unset PYTHONPATH

# Pick up EPICS environment variable settings just in case user did not
source /reg/g/pcds/setup/epics-ca-env.sh

# Source the bash setup
CONDA_ROOT="/reg/g/pcds/pyps/conda/py36"
source "${CONDA_ROOT}/etc/profile.d/conda.sh"

# Activate base env first so things like conda build are available
conda activate
# Default to dev pcds release
conda activate dev

EPICS_ROOT="/reg/g/pcds/epics-dev"

export PYTHONPATH=/reg/g/pcds/pyps/apps/dev/pythonpath
export PYQTDESIGNERPATH=/reg/g/pcds/pyps/conda/dev_designer_plugins/:$PYQTDESIGNERPATH
export PYDM_DESIGNER_ONLINE=1
export PYDM_DISPLAYS_PATH=$EPICS_ROOT/screens/pydm:$EPICS_ROOT
export PYDM_STYLESHEET=$EPICS_ROOT/screens/pydm/vacuumscreens/styleSheet/masterStyleSheet.qss
export PYDM_STYLESHEET_INCLUDE_DEFAULT=1
export LUCID_CONFIG=/reg/g/pcds/pyps/apps/hutch-python/lucid_config/
export HAPPI_CFG=/reg/g/pcds/pyps/apps/hutch-python/device_config/happi.cfg

# Revert to Software Raster when SSH to avoid issues with QtQuick.
# The same was done with PyDM and this fixes Designer and friends.
if [ -n "SSH_CONNECTION" ]; then
	echo "Using SSH, reverting QtQuick rendering to Software."
	export QT_QUICK_BACKEND="software"
fi

