#!/usr/bin/env bash
usage()
{
cat << EOF
usage: source $0

Source this to activate a shared in-development version of a pcds conda environment.
The environment provided by this is not guaranteed to be stable.
EOF
}

if [[ ($1 == "--help") || ($1 == "-h") ]]; then
	usage
	exit 0
fi


# Clear any PCDS_CONDA_VER to ensure we start from default in shared_conda_setup.sh
unset PCDS_CONDA_VER

# Target scripts in this directory, resolving symbolic links
THIS_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
# Add custom config file for putting dev- into prompt
export CONDARC="${THIS_DIR}/condarc.yaml"
# Load the shared elements, including whatever the default env is
source "${THIS_DIR}/shared_conda_setup.sh"

# Use PYTHONPATH to load dev modules on top of the default env
export PYTHONPATH="${APPS_ROOT}/dev/pythonpath"

# Strip out the installed prod stuff from the PYDM displays
# Before: pcdsdevices_prod:typhos_prod:pcdsdevices_dev:pydm_epics_dev:epics_dev
# After: pcdsdevices_dev:pydm_epics_dev:epics_dev
# This allows the pcdsdevices dev folder uis to be found before the installed tag
PYDM_DISPLAYS_PATH="$(cut -d ":" -f 3- <<< "${PYDM_DISPLAYS_PATH}")"
export PYDM_DISPLAYS_PATH

# In case you want to use this info
export IS_PCDS_CONDA=1
export IS_TAG_CONDA=0
export IS_DEV_CONDA=1
