#! /bin/bash
usage()
{
cat << EOF
usage: $0 options

start the eloggrabber, by default look at current exp

OPTIONS:
-e pass in an experiment to look at
-x instrument logbook
-c controls logbook
-u username
EOF
}

source /reg/g/psdm/sw/conda2/manage/bin/psconda.sh ""
export PYTHONPATH=/reg/g/psdm/web/ws/prod/apps/LogBookClient:${PYTHONPATH}
export PATH=/reg/g/psdm/web/ws/prod/apps/LogBookClient/LogBookClient:${PATH}

# This whole script should be thought about.  On one hand you can
# pass args to do more customizable things, but it's almost all automated
# on the other hand.  It makes it difficult to adhere to a convention amongst hutches
# and have any useful logic.

grab()
{
    if [[ $hutch == 'unknown_hutch' ]]; then
	echo 'I cannot determine the current hutch and thus not the current experiment. Try another machine (control room/psusr) or different directory like /reg/d/psdm/<hutch>/..... Will quit.'
	exit
    fi
    LogBookGrabber_qt \
	-i $HUTCH \
	-e $1 \
	-u $USERNAME \
	-p pcds \
	-w https://pswww.slac.stanford.edu/ws-auth/lgbk
    exit
}

# To try and avoid everything else going on
grab_script()
{
	LogBookGrabber_qt \
    -i $HUTCH \
    -e $1 \
    -u $USERNAME \
    -p pcds \
    -w https://pswww.slac.stanford.edu/ws-auth/lgbk \
    -c $SCRIPT
    exit
}

grab_user()
{
    LogBookGrabber_qt \
	-i $HUTCH \
	-e $1 \
	-u $USERNAME \
	-w https://pswww.slac.stanford.edu/ws-kerb/lgbk
    exit
}

grab_instrument()
{
    if [[ $hutch == 'unknown_hutch' ]]; then
	echo 'I cannot determine the current hutch and thus not the current experiment. Try another machine (control room/psusr) or different directory like /reg/d/psdm/<hutch>/..... Will quit.'
	exit
    fi
    EXPNAME="$HUTCH Instrument"
    LogBookGrabber_qt \
	-i OPS \
	-e "$EXPNAME" \
	-u $USERNAME \
	-p pcds \
	-w https://pswww.slac.stanford.edu/ws-auth/lgbk
    exit
}

grab_controls()
{
    EXPNAME="Controls"
    LogBookGrabber_qt \
	-i OPS \
	-e "$EXPNAME" \
	-u $USERNAME \
	-p pcds \
	-w https://pswww.slac.stanford.edu/ws-auth/lgbk
    exit
}

##who am I doing this? Why don't just use the actual username?
#USERNAME=`get_info --gethutch`opr
USERNAME=`whoami`
EXPNAME=current
hutch=`get_info --gethutch`

while getopts "e:u:hxct" OPTION
do
    case $OPTION in
	e)
	    EXPNAME=$OPTARG
	    hutch=${EXPNAME:0:3}
	    ;;
	u)
	    USERNAME=$OPTARG
	    grab_user $EXPNAME
	    ;;
	h)
	    usage
	    exit 1
	    ;;
	x)
	    grab_instrument
	    exit
	    ;;
	c)
	    grab_controls
	    exit
	    ;;
	?)
	    usage
	    exit
	    ;;
	esac
done

# hardcoding script running for now
if [[ $USERNAME == 'tmoopr' ]]
then
    HUTCH="tmo"
    SCRIPT='/cds/home/opr/tmoopr/bin/get_all.sh'
    grab_script $EXPNAME
    exit 1


if [[ $USERNAME == *'opr'* ]]; then
    grab $EXPNAME
else
    grab_user $EXPNAME
fi
