#!/usr/bin/env python
import requests
from requests.auth import HTTPBasicAuth
import argparse
import socket

def readRunTable(fname):
    runTableData={}
    with open(fname) as reader:
        lines = reader.readlines()
        for line in lines:
            try:
                print(line)
                runTableData[line.split()[0]]=line.split()[1]
            except:
                pass
    return runTableData

def postRunTableDict(runtable_data, experiment, run):
    args_url="https://pswww.slac.stanford.edu/ws-auth/lgbk/"
    ws_url = args_url + "/run_control/{0}/ws/add_run_params".format(experiment)
    print('URL:',ws_url)
    user=experiment[:3]+'opr'
    elogPostFile='/cds/home/opr/%s/forElogPost.txt'%user
    hostname=socket.gethostname()
    if hostname.find('sdf')>=0:
        elogPostFile='/sdf/group/lcls/ds/tools/forElogPost.txt'
    with open(elogPostFile,'r') as reader:
        answer = reader.readline()
    r = requests.post(ws_url, params={"run_num": run}, json=runtable_data, \
                      auth=HTTPBasicAuth(experiment[:3]+'opr', answer[:-1]))
    print(r)

def postRunTable(fname, experiment, run):
    print(fname, experiment, run)
    if fname=='pedestal':
        dataDict={'pedestal':'done'}
    else:
        dataDict = readRunTable(fname)
    print(dataDict)
    postRunTableDict(dataDict, experiment, run)

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('-r', '--run', help='run number',
                        required=True)
    parser.add_argument('-e', '--experiment', help='experiment name',
                        required=True)
    parser.add_argument('-f', '--file', help='file with data', required=True)
    args = parser.parse_args()

    postRunTable(args.file, args.experiment, args.run)

if __name__ == '__main__':
    main()
