#! /bin/bash
usage()
{
cat << EOF
usage: $0 options

start the eloggrabber, by default look at current exp

OPTIONS:
-e pass in an experiment to look at
-x instrument logbook
-u username
EOF
}

grab()
{
    if [[ $hutch == 'unknown_hutch' ]]; then
	echo 'I cannot determine the current hutch and thus not the current experiment. Try another machine (control room/psusr) or different directory like /reg/d/psdm/<hutch>/..... Will quit.'
	exit
    fi
    source /reg/g/psdm/sw/conda2/manage/bin/psconda.sh ""
    export PYTHONPATH=/reg/g/psdm/web/ws/prod/apps/LogBookClient:${PYTHONPATH}
    export PATH=/reg/g/psdm/web/ws/prod/apps/LogBookClient/LogBookClient:${PATH}
    LogBookGrabber_qt \
	-i $HUTCH \
	-e $1 \
	-u $USERNAME \
	-p pcds \
	-w https://pswww.slac.stanford.edu/ws-auth/lgbk
    exit
}

grab_user()
{
    source /reg/g/psdm/sw/conda2/manage/bin/psconda.sh ""
    export PYTHONPATH=/reg/g/psdm/web/ws/prod/apps/LogBookClient:${PYTHONPATH}
    export PATH=/reg/g/psdm/web/ws/prod/apps/LogBookClient/LogBookClient:${PATH}
    LogBookGrabber_qt \
	-i $HUTCH \
	-e $1 \
	-u $USERNAME \
	-w https://pswww.slac.stanford.edu/ws-kerb/lgbk
    exit
}

grab_instrument()
{
    if [[ $hutch == 'unknown_hutch' ]]; then
	echo 'I cannot determine the current hutch and thus not the current experiment. Try another machine (control room/psusr) or different directory like /reg/d/psdm/<hutch>/..... Will quit.'
	exit
    fi
    source /reg/g/psdm/sw/conda2/manage/bin/psconda.sh ""
    export PYTHONPATH=/reg/g/psdm/web/ws/prod/apps/LogBookClient:${PYTHONPATH}
    export PATH=/reg/g/psdm/web/ws/prod/apps/LogBookClient/LogBookClient:${PATH}
    EXPNAME="$HUTCH Instrument"
    LogBookGrabber_qt \
	-i NEH \
	-e "$EXPNAME" \
	-u $USERNAME \
	-p pcds \
	-w https://pswww.slac.stanford.edu/ws-auth/lgbk
    exit
}

##who am I doing this? Why don't just use the actual username?
#USERNAME=`get_info --gethutch`opr
USERNAME=`whoami`
EXPNAME=current
hutch=`get_info --gethutch`
HUTCH=${hutch^^}

while getopts "e:u:hxt" OPTION
do
    case $OPTION in
	e)
	    EXPNAME=$OPTARG
	    hutch=${EXPNAME:0:3}
	    HUTCH=${hutch^^}
	    ;;
	u)
	    USERNAME=$OPTARG
	    grab_user $EXPNAME
	    ;;
	h)
	    usage
	    exit 1
	    ;;
	x)
	    grab_instrument
	    exit
	    ;;
	?)
	    usage
	    exit
	    ;;
	esac
done

if [[ $USERNAME == *'opr'* ]]; then
    grab $EXPNAME
else
    grab_user $EXPNAME
fi
