#!/bin/bash
usage()
{
cat << EOF
usage: $0 options

OPTIONS:
-l add live status
-i/H information for hutch (override autodetection)
EOF
}

if [[ ($1 == "--help") || ($1 == "-h") ]]; then
	usage
	exit 0
fi

AskLive=0
Ended=0
INSTRUMENT='xxx'

DIR=$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")
PATH=$DIR:$PATH

while getopts "H:i:le" OPTION
do
    case $OPTION in
	l) 
	    AskLive=1
	    ;;
	e) 
	    Ended=1
	    ;;
	i) 
	    INSTRUMENT=$OPTARG
	    ;;
	H) 
	    INSTRUMENT=$OPTARG
	    ;;
	?)
	    usage
	    exit
	    ;;
	esac
done

if [ $AskLive -eq 1 ]; then
    if [ $INSTRUMENT != 'xxx' ]; then
	CURR_EXP=`get_info --hutch $INSTRUMENT --run --live`    
    else
	CURR_EXP=`get_info --run --live`    
	if [[ $CURR_EXP == *'xxx'* ]]; then
	    echo 'For which hutch would you like to get this information? '
	    read hutch
	    CURR_EXP=`get_info --hutch $hutch --run --live`
	fi
    fi
elif [ $Ended -eq 1 ]; then
    if [ $INSTRUMENT != 'xxx' ]; then
	CURR_EXP=`get_info --hutch $INSTRUMENT --run --ended`    
    else
	CURR_EXP=`get_info --run --ended`    
	if [[ $CURR_EXP == *'xxx'* ]]; then
	    echo 'For which hutch would you like to get this information? '
	    read hutch
	    CURR_EXP=`get_info --hutch $hutch --run --ended`
	fi
    fi
else
    if [ $INSTRUMENT != 'xxx' ]; then
	CURR_EXP=`get_info --hutch $INSTRUMENT --run`    
    else
	CURR_EXP=`get_info --run`
    fi
    NUM_RET_WORD=`echo $CURR_EXP | wc | awk {'print $2'}`
    if [ $NUM_RET_WORD == 1 ]; then
	if [ $CURR_EXP == 'xxx' ]; then
	    echo 'For which hutch would you like to get this information? '
	    read hutch
	    CURR_EXP=`get_info --hutch $hutch --run`
	fi
    fi
fi
echo $CURR_EXP
