#!/bin/bash

DIRTMP=`dirname  "${BASH_SOURCE[0]}"`
DIR="$( cd $DIRTMP && pwd -P )"
PATH=$PATH:$DIR

CURR_EXP=`get_info --exp`
if [ $# == 1 ]; then
    CURR_EXP=`get_info --hutch ${1^^} --exp`
elif [ $CURR_EXP == 'xxx' ]; then
    echo 'Cannot autodetermine hutch, for which hutch would you like to get this information? '
    read -t 5 hutch
    if [ $hutch == '' ]; then 
	echo 'no response, will quit'
	exit 1
    fi
    CURR_EXP=`get_info --hutch ${hutch^^} --exp`
fi
 
echo $CURR_EXP
