#!/bin/bash
usage()
{
cat << EOF
usage: $0 

Returns the hutch name based on the host it is run on
EOF
}

if [[ ($1 == "--help") || ($1 == "-h") ]]; then
	usage
	exit 0
fi

DIRTMP=`dirname  "${BASH_SOURCE[0]}"`
DIR="$( cd $DIRTMP && pwd -P )"
PATH=$PATH:$DIR

hutch=`get_info --gethutch`
echo $hutch
