#!/bin/bash
usage()
{
cat << EOF
usage: $0 

Returns the hutch name based on the host it is run on
EOF
}

if [[ ($1 == "--help") || ($1 == "-h") ]]; then
	usage
	exit 0
fi

DIR=$(readlink -f "$(dirname "${BASH_SOURCE[0]}")")
PATH=$DIR:$PATH

hutch=`get_info --gethutch`
echo $hutch
