#!/bin/bash

usage()
{
cat << EOF
usage: $0 options

OPTIONS:
-l add live status
EOF
}
AskLive=0
Ended=0

DIRTMP=`dirname  "${BASH_SOURCE[0]}"`
DIR="$( cd $DIRTMP && pwd -P )"
PATH=$PATH:$DIR

while getopts "hle" OPTION
do
    case $OPTION in
	h)
	    usage
	    exit 1
	    ;;
	l) 
	    AskLive=1
	    ;;
	e) 
	    Ended=1
	    ;;
	?)
	    usage
	    exit
	    ;;
	esac
done

if [ $AskLive -eq 1 ]; then
    CURR_EXP=`get_info --run --live`    
    if [[ $CURR_EXP == *'xxx'* ]]; then
	echo 'For which hutch would you like to get this information? '
	read hutch
	CURR_EXP=`get_info --hutch $hutch --run --live`
    fi
elif [ $Ended -eq 1 ]; then
    CURR_EXP=`get_info --run --ended`    
    if [[ $CURR_EXP == *'xxx'* ]]; then
	echo 'For which hutch would you like to get this information? '
	read hutch
	CURR_EXP=`get_info --hutch $hutch --run --ended`
    fi
else
    CURR_EXP=`get_info --run`
    NUM_RET_WORD=`echo $CURR_EXP | wc | awk {'print $2'}`
    if [ $NUM_RET_WORD == 1 ]; then
	if [ $CURR_EXP == 'xxx' ]; then
	    echo 'For which hutch would you like to get this information? '
	    read hutch
	    CURR_EXP=`get_info --hutch $hutch --run`
	fi
    fi
fi
echo $CURR_EXP
