#!/bin/bash
usage()
{
cat << EOF
usage: $0 

Print the EVR FW version for all EVR IOCs found in all IOC manager configurations.
EOF
}

if [[ ($1 == "--help") || ($1 == "-h") ]]; then
    usage
    exit 0
fi

for i in $(grep_ioc evr all | awk '/id:/ { print $2 }' | grep evr | cut -d\' -f2); do
pv=$(cat /cds/data/iocData/$i/iocInfo/IOC.pvlist | grep CTRL | grep \"er\" | cut -d, -f1)
val=$(caget -0x $pv.FPGV)
echo $i : $val
done
