#!/bin/bash
usage()
{
cat << EOF
usage: $0

Grep searches through IOC dirs in /reg/d/iocData/ for PVs that match keyword
Usage: $0 <PV or PV keyword>
EOF
}

if [[ $1 =~ ^(h|-h|-help|--help) ]]; then
	usage
	exit 0
fi

KEYWORD=$1

if [[ -n $1 ]]; then
    cd /reg/d/iocData/
    for i in ioc-*; do 
	cd /reg/d/iocData/$i
	if [ -e ./iocInfo/ ] ; then
     	    cd iocInfo
	    if [ -e ./IOC.pvlist ] ; then
		if grep -q $KEYWORD IOC.pvlist
		then 
		    pwd
		    grep $KEYWORD IOC.pvlist;
		    echo ""
		else
		    :
		fi
	    fi 
	fi
	cd ../../
    done
fi
