#!/bin/bash

usage() {
cat << EOF
greps hutch iocmanager config files for keyword
usage: $0 <keyword> [hutch]
hutch can be any of:
xpp, xcs, cxi, mfx, mec, xrt, aux, det, fee, hpl, icl, las, lfe, tst, thz, all
If no hutch is specified, all hutches will be searched
EOF
}

if [[ -z $1 ]]; then
    usage
    exit
fi
if [[ -z $2 ]]; then
    HUTCH="all"
else
    for hutchname in "xpp" "xcs" "cxi" "mfx" "mec" "xrt" "aux" "det" "fee" "hpl" "icl" "las" "lfe" "tst" "thz" "all"; do 
        if [[ "${2,,}" == $hutchname ]]; then
            HUTCH=$hutchname
        fi
    done
fi
if [[ -z $HUTCH ]]; then
    echo "incorrect hutch name given.  Enter hutch name in lower case (example: xpp)"
else
    if [[ $HUTCH == "all" ]]; then
        grep -i "${1}" /reg/g/pcds/pyps/config/*/iocmanager.cfg
    else
        grep -i "${1}" /reg/g/pcds/pyps/config/${HUTCH}/iocmanager.cfg
    fi
fi
