#!/bin/bash
usage()
{
    cat << EOF
Usage: $0 <PV or PV keyword>

Grep searches through IOC dirs in /cds/data/iocData/ for PVs that match keyword
EOF
}

if [[ ($1 == "--help") || ($1 == "-h") ]]; then
    usage
    exit 0
fi

KEYWORD=$1

if [[ -n $KEYWORD ]]; then
    cd /cds/data/iocData/
    for i in ioc-*; do
        cd /cds/data/iocData/"$i"
        if [ -e ./iocInfo/ ]; then
            cd iocInfo
            if [ -e ./IOC.pvlist ]; then
                if grep -q "$KEYWORD" IOC.pvlist; then
                    pwd
                    grep "$KEYWORD" IOC.pvlist
                    echo ""
                else
                    :
                fi
            fi
        fi
        cd ../../
    done
else
    usage
    exit 0
fi
