#!/bin/bash
usage()
{
    cat << EOF
usage: $0 <keyword> [hutch]

greps hutch iocmanager config files for keyword
hutch can be any of:
xpp, xcs, cxi, mfx, mec, tmo, rix, xrt, aux, det, fee, hpl, icl, las, lfe, kfe, tst, thz, all
If no hutch is specified, all hutches will be searched
EOF
}

if [[ ($1 == "--help") || ($1 == "-h") ]]; then
    usage
    exit 0
fi

if [[ -z $1 ]]; then
    usage
    exit
fi

if [[ -z $2 ]]; then
    HUTCH="all"
else
    for hutchname in "xpp" "xcs" "cxi" "mfx" "mec" "tmo" "rix" "xrt" "aux" "det" "fee" "hpl" "icl" "las" "lfe" "kfe" "tst" "thz" "all"; do
        if [[ ${2} == "$hutchname" ]]; then
            HUTCH=$hutchname
        fi
    done
fi
if [[ -z $HUTCH ]]; then
    echo "incorrect hutch name given.  Enter hutch name in lower case (example: xpp)"
else
    if [[ $HUTCH == "all" ]]; then
        grep -i "${1}" /reg/g/pcds/pyps/config/*/iocmanager.cfg
    else
        grep -i "${1}" /reg/g/pcds/pyps/config/"$HUTCH"/iocmanager.cfg
    fi
fi
