#!/usr/bin/bash
# Wrapper script for deploying IOCs from github.
# See ioc_deploy.py or try --help for usage
if ssh-add -L; then
    echo ""
    echo "WARNING: Your ssh key is not in the ssh agent."
    echo "         If you run ioc-deploy like this, you may need to input"
    echo "         your ssh key password multiple times!"
    echo "         Try 'source ssh-agent-helper' to input your ssh key"
    echo "         password only once per login."
    echo ""
fi

THIS_SCRIPT="$(realpath "${BASH_SOURCE[0]}")"
THIS_DIR="$(dirname "${THIS_SCRIPT}")"

# Run the deploy script
/usr/bin/python3 "${THIS_DIR}"/ioc_deploy.py "$@"
