#!/bin/bash
usage()
{
cat << EOF
usage: $0

iocmanager [hutch]

Control status of all IOCs running in a particular hutch in an interactive GUI.
Current hutch is used if not provided.
EOF
}

if [[ ($1 == "--help") || ($1 == "-h") ]]; then
	usage
	exit 0
fi

ulimit -c unlimited

source /reg/g/pcds/setup/pathmunge.sh
ldpathmunge /usr/local/lib

DIRTMP=`dirname  "${BASH_SOURCE[0]}"`
DIR="$( cd $DIRTMP && pwd -P )"
pathmunge $DIR
#PATH=$PATH:$DIR

if [ "$#" -ne 1 ]; then
    HUTCH=`get_hutch_name`
else
    HUTCH=$1
fi

/reg/g/pcds/pyps/config/${HUTCH}/iocmanager/IocManager --hutch $HUTCH > /dev/null &

if [ `whoami` == "xppopr" ]; then
    window_id=`xdotool search --sync --onlyvisible --name 'IocManager'` 
    if [ "xpp-control"  == "$HOSTNAME" ]; then
	wmctrl -v -i -r "$window_id" -e 0,3310,1100,530,1000
    elif [ "xpp-daq" == "$HOSTNAME" ]; then
	wmctrl -v -i -r "$window_id" -e 0,3310,1100,530,1000
    fi
    wmctrl -v -i -r "$window_id" -b add,sticky
fi
