#!/bin/bash

# Shell environment variables are now all loaded from scripts located
# in /reg/g/pcds/setup
#iocs/pvs live in/reg/d/iocData/ioc*/iocInfo/IOC.pvlist



usage(){
cat << EOF
usage: $0 ioc|pv [options]

Script that  returns information about an ioc given its name or a PV associated with it

Signature:
iocTool <ioc>|<pv> [command] #que es <ioc>|<pv>
d

default command is 'name', list of commands:
name : returns the name of the ioc
cfg : returns cfg file if it exists, otherwise st.cmd (path)
less : opens the cfg (or st.cmd) in less
dir : returns the directory the ioc is running from
cddir : open the directory the ioc is running from 
telnet : starts a telnet session with the ioc 
data : returns the path of the appropriate iocData directory if it exists


EOF
}

   
#<2 ---- error channel implementation needed 

#returning the name of the ioc given the pv or name itself

 #can be either a ioc or pv
if [$# -lt 1]; then
   echo  'need arguments: input ioc or pv name'
fi
	
NAME=$1
CMD=$2

#where a pv will be converted to an ioc

if [ $CMD == "name" ]; then
   echo "$NAME"

elif [ "dir" ]; then
   echo "grep_ioc $NAME all | grep "dir:''" 
   



fi
