#!/bin/bash

function kauth
{
    # If token doesn't exist, create it (will query for password)
    if ! klist -s; then
        while ! kinit -l 365d -r 365d; do
            :
        done
    else
        kinit -R &> /dev/null
    fi
    return 0
}

function afsauth
{
    # need to be in g-pcds afs group
    if ! pts membership g-pcds 2>&1 | grep -q "$(whoami)"; then
        echo "You do not have permission to use afs. See https://confluence.slac.stanford.edu/display/PCDS/Onboarding+Staff+Members"
        return 1
    fi

    # afs should be used from psbuild servers
    if [[ $(hostname) != psbuild-rhel* ]]; then
        echo "You must be on psbuild to create afs tokens"
        return 1
    fi

    # If token doesn't exist, create it
    if ! tokens | grep -q $UID; then
        # afs needs kerberos token
        kauth
        aklog
    fi
    return 0
}

# if name == '__main__':
if [[ ${BASH_SOURCE[0]} == "${0}" ]]; then
    afsauth
fi
