#!/bin/bash

function kauth {
    # If token doesn't exist, create it (will query for password)
    if ! klist -s
    then
	while ! kinit
	do
            :
	done
    fi
}

function afsauth {
    # afs needs kerberos token
    kauth
    # only available on psbuild servers
    if [[ $(hostname) != psbuild-rhel* ]]
    then
        echo "You must be on psbuild to create afs tokens"
	exit
    fi

    # need to be in g-pcds afs grup
    if ! pts membership g-pcds 2>&1 | grep -q "$(whoami)"
    then
        echo "You do not have permission to use afs. See https://confluence.slac.stanford.edu/display/PCDS/Onboarding+Staff+Members"
        exit
    fi

    # If token doesn't exist, create it
    if ! tokens | grep -q $UID
    then	
        aklog
    fi
}

# if name == '__main__':
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    afsauth
fi
