#! /bin/bash

DIRTMP=$(dirname  "$(readlink -f "${BASH_SOURCE[0]}")")
DIR="$( cd $DIRTMP && pwd -P )"
PATH=$PATH:$DIR

usage()
{
cat << EOF
usage: $0 options

Make a pedestal file for offline use

OPTIONS:
-u user (needs to be able to log into the psananeh/feh)
-r runnumber for pedestal
-e <expname> in case you do not want pedestals for the ongoing experiment
-J make pedestals for Jungfrau (default only cspad/EPIX detectors)
-O make pedestals for Opals (default only cspad/EPIX detectors)
-Z make pedestals for Zyla (default only cspad/EPIX detectors)
-p <text>: add <text> to elog post
-c <evtcode x> use events with eventcode <x> set
-n # : if you have created a noise file, then write pixel mask file for pixels with noise above #sigma
-N # : use this number of events (default 1000)
-D : dark run for XTCAV
-L : lasing off run for XTCAV
-v <str>: validity range (if not run#-end, e.g. 123-567 or 123-end)
-l: do NOT send to batch queue
-F : use the FFB (default if no experiment is passed)
-f : full epix10k charge injection run
-C # : if noise filecreated, write pixel mask file for pixels with noise below xxx (currently integer only...)
-m # : write pixel mask file for pixels with pedestal below xxx (currently integer only...)
-x # : write pixel mask file for pixels with pedestal above xxx (currently integer only...)
-i start calibman. -r 0: show all darks, -r n: show runs (n-25) - 25
-d give path for alternative calibdir
EOF
}

USER=`whoami`
RUN=0
EXP='xxx'
RUNLOCAL=0
GETFFBNODE=0
RUNFFBNODE=0
FFBNODE=psana1609
VALSTR='xxx'
NUMEVT=1000
SPEC_ARG=''
INTERACTIVE=0
elogMessage="DARK"
ELOGTEXT=""

while getopts "u:r:e:n:p:c:v:N:m:x:d:C:DLZOJEiltfFgh" OPTION
do
    case $OPTION in
	h)
	    usage
	    exit 1
	    ;;
	u)
	    USER=$OPTARG
	    ;;
	r)
	    RUN=$OPTARG
	    ;;
	e)
	    EXP=$OPTARG
	    ;;
	c)
	    SPEC_ARG=$SPEC_ARG' -c '$OPTARG
	    ;;
	d)
	    SPEC_ARG=$SPEC_ARG' -d '$OPTARG
	    ;;
	n)
	    SPEC_ARG=$SPEC_ARG' -n '$OPTARG
	    ;;
	f)
	    SPEC_ARG=$SPEC_ARG' -f '
	    ;;
	F)
	    GETFFBNODE=1
	    RUNFFBNODE=1
	    SPEC_ARG=$SPEC_ARG' -F '
	    ;;
	v)
	    VALSTR=$OPTARG
	    ;;
	N)
	    NUMEVT=$OPTARG
	    ;;
	D)
	    SPEC_ARG=$SPEC_ARG' -D '
	    elogMessage="DARK for XTCAV"
	    ;;
	L)
	    SPEC_ARG=$SPEC_ARG' -L '
	    elogMessage="Lasing Off for XTCAV"
	    ;;
	i)
	    SPEC_ARG=$SPEC_ARG' -i '
	    ;;
	Z)
	    SPEC_ARG=$SPEC_ARG' -Z '
	    elogMessage="DARK for Zyla"
	    ;;
	O)
	    SPEC_ARG=$SPEC_ARG' -O '
	    elogMessage="DARK for Opal"
	    ;;
	J)
	    SPEC_ARG=$SPEC_ARG' -J '
	    elogMessage="DARK for jungfrau, also next two runs."
	    ;;
	E)
	    SPEC_ARG=$SPEC_ARG' -E '
	    elogMessage="DARK for epix10k "
	    ;;
	l)
	    SPEC_ARG=$SPEC_ARG' -l '
	    ;;
	t)
	    SPEC_ARG=$SPEC_ARG' -t '
	    ;;
	p)
	    ELOGTEXT=$OPTARG
	    ;;
	g)
	    GETFFBNODE=1
	    SPEC_ARG=$SPEC_ARG' -l '
	    ;;
	C)
	    SPEC_ARG=$SPEC_ARG' -C '$OPTARG
	    ;;
	m)
	    SPEC_ARG=$SPEC_ARG' -m '$OPTARG
	    ;;
	x)
	    SPEC_ARG=$SPEC_ARG' -x '$OPTARG
	    ;;
	?)
	    usage
	    exit
	    ;;
    esac
 done

if [[ $USER =~ "opr" ]]; then
     printf "Please enter user name (cannot run as from operator account): \n"; read USER
 fi

 if [ $GETFFBNODE -eq 1 ]; then
     #only if local:
     if [[ $SPEC_ARG == *' -l'* ]]; then
         printf "Please enter ffb node name (suggested psana1609): \n"; read FFBNODE
         if [ `echo $FFBNODE | wc -c` -le 1 ]; then
             FFBNODE=psana1609
         fi    
     else
         RUNFFBNODE=0
     fi
    
     ##find an empty node.
     #FFBNODE_LINE=`ssh -Y $USER@psdev ssh -Y psana "bhosts psnehfarm | grep ok | tail -n1 "`
     #echo A $FFBNODE_LINE XX
     #if [ `echo $FFBNODE_LINE |  wc -w ` -eq 0 ]; then
     #	 echo check feh
     #	 FFBNODE_LINE=`ssh -Y $USER@psdev ssh -Y psana "bhosts psfehfarm | grep ok | tail -n1 "`
     #fi
     #echo B $FFBNODE_LINE XX
     ##accept a full, but working node.
     #echo C $FFBNODE_LINE
     #if [ `echo $FFBNODE_LINE |  wc -w ` -eq 0 ]; then
     #	 FFBNODE_LINE=`ssh -Y $USER@psdev ssh -Y psana "bhosts pshehfarm | grep Full | tail -n1 "`
     #fi
     #if [ `echo $FFBNODE_LINE |  wc -w ` -eq 0 ]; then
     #	 FFBNODE_LINE=`ssh -Y $USER@psdev ssh -Y psana "bhosts psfehfarm | grep Full | tail -n1 "`
     #fi
     #FFBNODE=`echo $FFBNODE_LINE |  awk '{print $1}'`
     #echo 'for interactive sessions, use: '$FFBNODE
     #if [ $RUNFFBNODE -ne 1 ]; then
     #	 echo 'do not want to run on ffb node, so I will QUIT here '
     #	 exit
     #fi
 fi

 if [ $RUN == 0 ]; then
    if [ $INTERACTIVE -ne 1 ]; then
	printf "Please enter a run number: \n"; read RUN
    fi
fi

COMMAND_ARGS=' -r '$RUN' -N '$NUMEVT
if [ $EXP != 'xxx' ]; then
    COMMAND_ARGS=$COMMAND_ARGS' -e '$EXP
    HUTCH=${EXP:0:3}
else
    #no experiment was passed, default to using the FFB
    HUTCH=`get_info --gethutch`
    EXP=`get_info --exp --hutch $HUTCH`
    COMMAND_ARGS=$COMMAND_ARGS' -H '$HUTCH' -e '$EXP' -F'
    if [[ $SPEC_ARG == *' -l'* ]]; then
	RUNFFBNODE=1
    fi
fi

if [ $VALSTR != 'xxx' ]; then
    COMMAND_ARGS=$COMMAND_ARGS' -v '$VALSTR
fi

COMMAND_ARGS=$COMMAND_ARGS$SPEC_ARG

if [ $RUNFFBNODE -ne 0 ]; then
    echo calling on $FFBNODE makepeds_psana $COMMAND_ARGS
    ssh -Y $USER@psdev ssh -Y $FFBNODE "$DIR/makepeds_psana $COMMAND_ARGS"
else
    echo calling:  makepeds_psana $COMMAND_ARGS
    if [[ $HOSTNAME =~ "psana" ]]; then
	    $DIR/makepeds_psana $COMMAND_ARGS
    else
	ssh -Y $USER@psdev ssh -Y psana "$DIR/makepeds_psana $COMMAND_ARGS"
    fi
fi

elogMessage+=$ELOGTEXT
source pcds_conda

# Need the following line until the controls conda is updated to pick up the latest elog package.
export PYTHONPATH=/reg/g/pcds/pyps/apps/hutch-python/common/dev/elog:${PYTHONPATH}
BINPATH=/reg/g/pcds/pyps/conda/py36/envs/pcds-3.3.1/bin/python
PYCMD=/reg/g/pcds/pyps/apps/hutch-python/common/dev/elog/scripts/LogBookPost.py
if [[ `whoami` =~ "opr" ]]; then
    echo $BINPATH $PYCMD -i "${HUTCH^^}" -u `whoami` -e "$EXP"  -t DARK  -r $RUN -m "$elogMessage"
    if [[ $HOSTNAME == 'cxi-monitor' ]]; then
        $BINPATH $PYCMD -i "${HUTCH^^}" -u `whoami` -p pcds -e "$EXP"  -t DARK  -r $RUN -m "$elogMessage" -s 1&
    else
        $BINPATH $PYCMD -i "${HUTCH^^}" -u `whoami` -p pcds -e "$EXP"  -t DARK  -r $RUN -m "$elogMessage"&
    fi
else
    echo $BINPATH $PYCMD -i "${HUTCH^^}" -e "$EXP"  -t DARK -r $RUN -m "$elogMessage"
    if [[ $HOSTNAME == 'cxi-monitor' ]]; then
        $BINPATH $PYCMD -i "${HUTCH^^}" -e "$EXP" -t DARK -r $RUN -m "$elogMessage" -s 1&
    else
        $BINPATH $PYCMD -i "${HUTCH^^}" -e "$EXP" -t DARK -r $RUN -m "$elogMessage"&
    fi
fi
