#!/bin/bash
usage()
{
cat << EOF
usage: new_bare_repo <hutch> <repo name>

Script for automating the tedious process of integrating an existing IOC into our git bare repo scheme
Run in the top level of your IOC

Ex. new_bare_repo rix new_device
(Creates a new bare repo in /afs/slac.stanford.edu/g/cd/swe/git/repos/package/epics/ioc/rix/ named "new_device.git")

You also might need to run kinit and aklog before hand!

EOF
}

if [[ ($1 == "--help") || ($1 == "-h") ]]; then
   usage
   exit 0

elif [ $# -lt 2 ]; then
   echo 'Need to specify the hutch and name of the proposed bare repo' >&2
   usage
   exit 1

fi

HUTCH=$1
REPO=$2
CWD=$PWD

set -e
if [ ! -d "/afs/slac.stanford.edu/g/cd/swe/git/repos/package/epics/ioc/${HUTCH}/" ]; then
    echo "The directory /afs/slac.stanford.edu/g/cd/swe/git/repos/package/epics/ioc/${HUTCH}/ does not exist!"
    exit 1
elif [ -d "/afs/slac.stanford.edu/g/cd/swe/git/repos/package/epics/ioc/${HUTCH}/${REPO}.git" ]; then
    echo "There already exists a bare repo for this device!"
    exit 1
elif [[ ${CWD} != *${REPO}* ]]; then
    echo "Current working directory does not contain the name of the planned repo, check that you are running this script in the right place"
    exit 1
else
    git init
    cp -u /cds/sw/tools/bin/eco_tools/gitignore.template .gitignore
    git add *.cfg Makefile .gitignore
    git commit -m "Initial commit"
    git-bare-repo /afs/slac.stanford.edu/g/cd/swe/git/repos/package/epics/ioc/"${HUTCH}"/"${REPO}".git
    git remote add origin /afs/slac.stanford.edu/g/cd/swe/git/repos/package/epics/ioc/"${HUTCH}"/"${REPO}".git
fi
