#!/bin/bash
usage()
{
cat << EOF
usage: $0

$0 [hutch] [--debug] [--applyenable]

--debug	: Displays the debug button, which prints out any edits made
--applyenable : Displays the apply all button, which applies settings to all motors
EOF
}

if [[ $1 =~ ^(h|-h|-help|--help) ]]; then
	usage
	exit 0
fi

if [[ -n $1 && ! $1 =~ '--' ]]; then
    HUTCH=$1
    shift
else
    HUTCH=`get_hutch_name`
fi
/reg/g/pcds/pyps/config/${HUTCH}/pmgr/pmgr --type ims_motor --hutch ${HUTCH} $@ &
