#!/bin/bash
usage()
{
cat << EOF
usage: $0

$0 <path> <module or bin>

Use this script to register development packages so that they will be
available when you source pydev_env
EOF
}

if [[ ($1 == "--help") || ($1 == "-h") ]]; then
	usage
	exit 0
fi

if [ -z "${1}" ]; then
  usage
  exit
fi
PYDEV_DIR=~/pydev
full_path="$(readlink -f $1)"
if [ "${2}" == "module" ]; then
  link="${PYDEV_DIR}"
elif [ "${2}" == "bin" ]; then
  link="${PYDEV_DIR}/bin"
else
  echo "Invalid input."
  usage
  return
fi
mkdir -p "${PYDEV_DIR}/bin"
ln -sf "${full_path}" "${link}"
