#! /usr/bin/env bash

HUTCH=`get_hutch_name`
EXPNAME=`get_curr_exp`
#
# this is XPP specific. Don't think we should have local plugins anyways, 
# only release ones. 
#
source /reg/g/pcds/setup/pathmunge.sh
ldpathmunge /reg/neh/operator/xppopr/ami_plugins
ldpathmunge /reg/neh/operator/xcsopr/online/ami_plugins

usage()
{
cat << EOF
usage: $0 options

we are starting another ami session here

OPTIONS:
-s: stop the ami client current running on this machine
EOF
}

STOP_AMI=0
while getopts "h:s" OPTION
do
    case $OPTION in
	h)
	    usage
	    exit 1
	    ;;
	s)
	    stopami
	    ;;
	?)
	    usage
	    exit
	    ;;
	esac
done

DAQHOST=`wheredaq`

ami_base_path=`grep ami_base_path /reg/g/pcds/dist/pds/$HUTCH/scripts/$HUTCH.cnf | grep -v '#' | grep -v 'ami_base_path+'  | awk 'BEGIN { FS = "=" }; { print $2}' | sed s/\'//g`
ami_path=$ami_base_path`grep amiRH5_path /reg/g/pcds/dist/pds/$HUTCH/scripts/$HUTCH.cnf | grep -v 'amiRH5_path+' | grep -v '#' | awk 'BEGIN { FS = "= " }; { print $2}' | sed s/ami_base_path+// | sed s/\'//g`
proxy_node=`grep 'proxy_node ' /reg/g/pcds/dist/pds/$HUTCH/scripts/$HUTCH.cnf | grep -v procmg | grep -v \# | awk {'print $3'} | sed s/_/-/g`
netconfig search $proxy_node | grep IP | sed 's/IP: //g' | sed 's/\t172/172/g' > /tmp/amiProxy_IP
proxy_cds=`grep 172 /tmp/amiProxy_IP`
rm /tmp/amiProxy_IP
amicmd=`grep ami_client /reg/g/pcds/dist/pds/$HUTCH/scripts/$HUTCH.cnf | grep -v '#' |  awk 'BEGIN { FS = ":" }; { print $4}' | sed s/xppopr/$HUTCH\opr/| sed s/amiRH5_path//g | sed s/\'+proxy_cds/$proxy_cds/g | sed  s:\'+expname:$EXPNAME/:g | sed s/+\'//g | sed s/\'\}\)//g` 

if [ $HOSTNAME == $DAQHOST ]; then
    #running on the DAQ host, this will restart the ami_client!
    read -p "Do you really intend to restart the ami_client on $DAQHOST? (y/n)"
    if [ "$REPLY" == "y" ];then
	echo "Restarting the ami_client...";
	/reg/g/pcds/dist/pds/tools/procmgr/procmgr stop \
	    /reg/g/pcds/dist/pds/$HUTCH/scripts/$HUTCH.cnf ami_client 
	/reg/g/pcds/dist/pds/tools/procmgr/procmgr start \
 	    /reg/g/pcds/dist/pds/$HUTCH/scripts/$HUTCH.cnf -c 2000000000 -o /reg/g/pcds/pds/$HUTCH/logfiles ami_client 
	exit
    else
	read -p "Do you want to start a second client on the DAQ host $DAQHOST? (y/n)"
	if [ "$REPLY" == "n" ];then
	    exit
	else
	    echo "Starting another ami_client on "$DAQHOST , calling:
	fi
    fi
else
    echo --- connect to proxy on: $proxy_cds, calling:
fi    

echo $ami_path$amicmd
exec $ami_path$amicmd&
