#!/bin/bash
usage()
{
cat << EOF
usage: $0

Stop the daq in the current hutch.
EOF
}

if [[ ($1 == "--help") || ($1 == "-h") ]]; then
	usage
	exit 0
fi

HUTCH=`get_info --gethutch`
DAQHOST=`wheredaq`
CNFEXT=.cnf
if [ $HOSTNAME == 'cxi-daq' ]; then
    CNFEXT=_0.cnf
elif [ $HOSTNAME == 'cxi-monitor' ]; then
    CNFEXT=_1.cnf
fi

if [[ $DAQHOST != 'DAQ is not running' ]]; then
    T="$(date +%s%N)"
    echo stop the DAQ from $HOSTNAME
    /reg/g/pcds/dist/pds/tools/procmgr/procmgr stop \
	/reg/g/pcds/dist/pds/$HUTCH/scripts/$HUTCH$CNFEXT 
    #source /reg/g/pcds/dist/pds/$HUTCH\/scripts/stop_$HUTCH\_daq.csh

    PLATFORM=`grep 'if not platform' /reg/g/pcds/dist/pds/$HUTCH/scripts/$HUTCH$CNFEXT | awk '{print $NF}' | sed s/\'//g`
    if [ -f /reg/g/pcds/dist/pds/$HUTCH/scripts/p$PLATFORM$CNFEXT.running ]; then
	echo 'the DAQ did not stop properly, exit now and try again or call Silke or the DAQ phone'
	exit
    fi
    T2="$(($(date +%s%N)-T))"
    S="$((T2/1000000000))"
    M="$((T2/1000000))"
    echo 'it took '$S'.'$M' to stop the DAQ'
else
    echo DAQ is currently not running
fi
