#!/bin/bash

usage()
{
cat << EOF
usage: $0

Takes a run with dark images for use in pedestals, and posts to the elog.

EOF
}

if [[($1 == "--help") || ($1 == "-h")]]; then
        usage
        exit 0
fi

DAQ_RELEASE=/cds/group/pcds/dist/pds/current

# -R: for norecord , -r forces recording
station=$(get_info --getstation)
$DAQ_RELEASE/tools/scanning/take_pedestals -p $station -r

elogMessage="DARK"
source pcds_conda
PYCMD=LogBookPost

EXP=`get_curr_exp`
RUN=`get_lastRun`
HUTCH=${EXP:0:3}
echo $PYCMD -i "${HUTCH^^}" -u `whoami` -e "$EXP"  -t DARK  -r $RUN -m "$elogMessage"
$PYCMD -i "${HUTCH^^}" -u `whoami` -p pcds -e "$EXP"  -t DARK  -r $RUN -m "$elogMessage"&

echo 'please call: makepeds -r '`get_lastRun`' -u <userID>'
echo 'for gain-switching detectors we recommend: makepeds -u <userID> -q milano -r '`get_lastRun`
#echo 'we need to use the offline data to process pedestals right now, make sure files have moved, otherwise a very silent failure might happen'
#echo 'please call: makepeds -u <userID> -e '`get_curr_exp`' -r '`get_lastRun`' -q psfehhiprioq'

