#!/bin/bash
HUTCH=`get_info --gethutch`
NOTRUNNING='Not running'

if  [ $HUTCH == 'cxi' ]; then
    if [ $HOSTNAME == 'cxi-daq' ]; then
	STATUS=`/reg/g/pcds/dist/pds/$HUTCH/current/tools/procmgr/procmgr status /reg/g/pcds/dist/pds/$HUTCH/scripts/$HUTCH\_0.cnf control_gui | grep started`
	if [[ $STATUS == *$NOTRUNNING* ]]; then
	    echo 'cxi_0 - ' $STATUS
	else
	    echo 'cxi_0 - Main DAQ is running on '$HOSTNAME
	fi
    elif [ $HOSTNAME == 'cxi-monitor' ]; then
	STATUS=`/reg/g/pcds/dist/pds/$HUTCH/current/tools/procmgr/procmgr status /reg/g/pcds/dist/pds/$HUTCH/scripts/$HUTCH\_1.cnf | grep started`
	if [[ $STATUS == *$NOTRUNNING* ]]; then
	    echo 'cxi_1  - Secondary DAQ is not running'
	else
	    echo 'cxi_1 - Secondary DAQ is running on '$HOSTNAME
	fi
    else 
	echo 'This machine ('$HOSTNAME') is not a cxi DAQ host'
    fi
    exit
fi

STATUS=`/reg/g/pcds/dist/pds/$HUTCH/current/tools/procmgr/procmgr status /reg/g/pcds/dist/pds/$HUTCH/scripts/$HUTCH.cnf control_gui | grep started`
if [[ $STATUS == *$NOTRUNNING* ]]; then
    echo 'DAQ in ' ${HUTCH^^}': ' $STATUS
    exit
else
   HOST=`echo $STATUS | awk {'print $5'}`
   echo $HOST
fi

