#!/bin/bash
HUTCH=`get_info --gethutch`
if [ $HUTCH == 'xpp' ]; then
   HOSTS="xpp-daq xpp-control xpp-hutch01"
elif  [ $HUTCH == 'xcs' ]; then
   HOSTS="xcs-daq xcs-control xcs-hutch01"
elif  [ $HUTCH == 'mfx' ]; then
   HOSTS="mfx-daq mfx-monitor"
elif  [ $HUTCH == 'cxi' ]; then
   HOSTS="cxi-daq cxi-monitor"
elif  [ $HUTCH == 'sxr' ]; then
   HOSTS="sxr-daq sxr-monitor sxr-console"
elif  [ $HUTCH == 'mec' ]; then
   HOSTS="mec-daq mec-console"
else
   echo 'could not determine hutch or hutch not implemented, quit'
   exit
fi

STATUS=`/reg/g/pcds/dist/pds/tools/procmgr/procmgr status /reg/g/pcds/dist/pds/$HUTCH/scripts/$HUTCH.cnf | grep started`
RUNNING='Not running'
if [[ $STATUS == *$RUNNING* ]]; then
    echo 'DAQ is not running in hutch ' $HUTCH
    exit
fi

for HOST in $HOSTS;
do
    daqhost=''
    if [[ $STATUS == *$HOST* ]]
    then
	daqhost=$HOST
    fi
    if [ ${#daqhost} != 0 ] 
    then
	echo $HOST
	break
    fi
done

