#!/bin/bash
usage()
{
cat << EOF
usage: $0

Discover what host is running the daq in the current hutch, if any.
EOF
}

if [[ ($1 == "--help") || ($1 == "-h") ]]; then
	usage
	exit 0
fi

HUTCH=`get_info --gethutch`
CNFEXT=.cnf
PLATFORM=0
if [ $HOSTNAME == 'cxi-monitor' ]; then
    PLATFORM=1
elif [ $HUTCH == 'rix' ]; then
    PLATFORM=2
fi

if [[ ! -f /reg/g/pcds/dist/pds/$HUTCH/scripts/p$PLATFORM.cnf.running ]]; then
    if [ $HOSTNAME == 'cxi-daq' ]; then
	echo 'Main DAQ cxi_0 is not running on $HOSTNAME '
    elif [ $HOSTNAME == 'cxi-monitor' ]; then
	echo 'Secondary DAQ cxi_1 is not running on $HOSTNAME '
    else
	echo 'DAQ is not running in '$HUTCH
    fi
else
    DAQ_HOST=`grep HOST /reg/g/pcds/dist/pds/$HUTCH/scripts/p$PLATFORM.cnf.running | awk {'print $3'} | sed s/\'//g`
    echo 'DAQ is running on '$DAQ_HOST
fi
